"""core domain platform

Revision ID: bf568d045965
Revises: 0001_cross_cutting
Create Date: 2026-08-27 20:49:54.197809
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bf568d045965'
down_revision: Union[str, None] = '0001_cross_cutting'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', name='adminrole', native_enum=False, create_constraint=True, length=16), server_default='editor', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('certifications',
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('credential_id', sa.String(length=200), nullable=True),
    sa.Column('credential_url', sa.String(length=2048), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_on IS NULL OR issued_on IS NULL OR expires_on >= issued_on', name='ck_certification_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index('ix_certifications_public_order', 'certifications', ['status', 'is_visible', 'sort_order'], unique=False)
    op.create_index(op.f('ix_certifications_status'), 'certifications', ['status'], unique=False)
    op.create_table('education',
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('credential', sa.String(length=200), nullable=False),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('achievements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_education_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index('ix_education_public_dates', 'education', ['status', 'is_visible', 'start_date'], unique=False)
    op.create_index(op.f('ix_education_status'), 'education', ['status'], unique=False)
    op.create_table('experiences',
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('employment_type', sa.String(length=80), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('achievements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_experience_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index('ix_experiences_public_dates', 'experiences', ['status', 'is_visible', 'start_date'], unique=False)
    op.create_index(op.f('ix_experiences_status'), 'experiences', ['status'], unique=False)
    op.create_table('feature_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index(op.f('ix_feature_settings_archived_at'), 'feature_settings', ['archived_at'], unique=False)
    op.create_index(op.f('ix_feature_settings_key'), 'feature_settings', ['key'], unique=True)
    op.create_table('homepage_sections',
    sa.Column('section_type', sa.Enum('hero', 'resume', 'availability', 'what_i_build', 'categories', 'selected_work', 'metrics', 'testimonials', 'sectors', 'skills', 'experience', 'education', 'certifications', 'open_source', 'sponsorship', 'writing', 'assistant', 'contact', 'social_links', 'editorial', name='homepagesectiontype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('variant', sa.String(length=80), server_default='default', nullable=False),
    sa.Column('animation_variant', sa.String(length=80), nullable=True),
    sa.Column('data_limit', sa.Integer(), nullable=True),
    sa.Column('show_cta', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('theme', sa.String(length=80), nullable=True),
    sa.Column('feature_key', sa.String(length=120), nullable=True),
    sa.Column('configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index(op.f('ix_homepage_sections_feature_key'), 'homepage_sections', ['feature_key'], unique=False)
    op.create_index('ix_homepage_sections_public_order', 'homepage_sections', ['status', 'is_visible', 'position'], unique=False)
    op.create_index(op.f('ix_homepage_sections_status'), 'homepage_sections', ['status'], unique=False)
    op.create_index('uq_homepage_sections_position', 'homepage_sections', ['position'], unique=True)
    op.create_table('login_attempts',
    sa.Column('identifier_digest', sa.String(length=64), nullable=False),
    sa.Column('ip_digest', sa.String(length=64), nullable=False),
    sa.Column('succeeded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_occurred_at'), 'login_attempts', ['occurred_at'], unique=False)
    op.create_index('ix_login_attempts_identifier_recent', 'login_attempts', ['identifier_digest', 'occurred_at'], unique=False)
    op.create_index('ix_login_attempts_ip_recent', 'login_attempts', ['ip_digest', 'occurred_at'], unique=False)
    op.create_index('ix_login_attempts_throttle', 'login_attempts', ['identifier_digest', 'ip_digest', 'occurred_at', 'succeeded'], unique=False)
    op.create_table('media_assets',
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_media_assets_public', 'media_assets', ['status', 'is_visible', 'created_at'], unique=False)
    op.create_index(op.f('ix_media_assets_status'), 'media_assets', ['status'], unique=False)
    op.create_table('navigation_items',
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('href', sa.String(length=2048), nullable=False),
    sa.Column('location', sa.String(length=40), server_default='header', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('open_in_new_tab', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index(op.f('ix_navigation_items_status'), 'navigation_items', ['status'], unique=False)
    op.create_index('ix_navigation_public_order', 'navigation_items', ['location', 'status', 'is_visible', 'sort_order'], unique=False)
    op.create_table('professional_categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('icon_key', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index('ix_categories_public_order', 'professional_categories', ['status', 'is_visible', 'sort_order'], unique=False)
    op.create_index(op.f('ix_professional_categories_slug'), 'professional_categories', ['slug'], unique=True)
    op.create_index(op.f('ix_professional_categories_status'), 'professional_categories', ['status'], unique=False)
    op.create_table('profiles',
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('headline', sa.String(length=240), nullable=False),
    sa.Column('short_bio', sa.Text(), nullable=False),
    sa.Column('long_bio', sa.Text(), nullable=True),
    sa.Column('public_location', sa.String(length=160), nullable=True),
    sa.Column('availability_status', sa.String(length=80), nullable=True),
    sa.Column('availability_detail', sa.String(length=300), nullable=True),
    sa.Column('public_email', sa.String(length=320), nullable=True),
    sa.Column('primary_cta_label', sa.String(length=80), nullable=True),
    sa.Column('primary_cta_url', sa.String(length=2048), nullable=True),
    sa.Column('secondary_cta_label', sa.String(length=80), nullable=True),
    sa.Column('secondary_cta_url', sa.String(length=2048), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index(op.f('ix_profiles_status'), 'profiles', ['status'], unique=False)
    op.create_index('uq_profiles_primary', 'profiles', ['is_primary'], unique=True, postgresql_where=sa.text('is_primary'), sqlite_where=sa.text('is_primary = 1'))
    op.create_table('sectors',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('icon_key', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index('ix_sectors_public_order', 'sectors', ['status', 'is_visible', 'sort_order'], unique=False)
    op.create_index(op.f('ix_sectors_slug'), 'sectors', ['slug'], unique=True)
    op.create_index(op.f('ix_sectors_status'), 'sectors', ['status'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_sessions_admin_user_id'), 'admin_sessions', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_sessions_expires_at'), 'admin_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_admin_sessions_token_hash'), 'admin_sessions', ['token_hash'], unique=True)
    op.create_index('ix_admin_sessions_user_active', 'admin_sessions', ['admin_user_id', 'expires_at', 'revoked_at'], unique=False)
    op.create_table('articles',
    sa.Column('hero_media_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=260), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('topics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reading_minutes', sa.Integer(), nullable=True),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hero_media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index(op.f('ix_articles_hero_media_id'), 'articles', ['hero_media_id'], unique=False)
    op.create_index('ix_articles_public_date', 'articles', ['status', 'is_visible', 'published_at'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_table('experience_sectors',
    sa.Column('experience_id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'sector_id')
    )
    op.create_table('portrait_assets',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_portrait_assets_profile_id'), 'portrait_assets', ['profile_id'], unique=False)
    op.create_index('ix_portrait_assets_profile_order', 'portrait_assets', ['profile_id', 'sort_order'], unique=False)
    op.create_index('uq_portrait_primary_per_profile', 'portrait_assets', ['profile_id'], unique=True, postgresql_where=sa.text('is_primary AND is_active'), sqlite_where=sa.text('is_primary = 1 AND is_active = 1'))
    op.create_table('projects',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('architecture', sa.Text(), nullable=True),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('decisions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tradeoffs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('challenges', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outcomes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('repository_url', sa.String(length=2048), nullable=True),
    sa.Column('live_url', sa.String(length=2048), nullable=True),
    sa.Column('is_open_source', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('featured_rank', sa.Integer(), nullable=True),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_project_dates'),
    sa.CheckConstraint('featured_rank IS NULL OR featured_rank > 0', name='ck_project_featured_rank'),
    sa.ForeignKeyConstraint(['category_id'], ['professional_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('featured_rank'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index(op.f('ix_projects_category_id'), 'projects', ['category_id'], unique=False)
    op.create_index('ix_projects_public_date', 'projects', ['status', 'is_visible', 'start_date'], unique=False)
    op.create_index('ix_projects_public_featured', 'projects', ['status', 'is_visible', 'featured_rank'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('resume_versions',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('download_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_resume_versions_profile_created', 'resume_versions', ['profile_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_resume_versions_profile_id'), 'resume_versions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_resume_versions_status'), 'resume_versions', ['status'], unique=False)
    op.create_index('uq_resume_current', 'resume_versions', ['is_current'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current = 1'))
    op.create_table('skills',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_key', sa.String(length=120), nullable=True),
    sa.Column('proficiency_label', sa.String(length=80), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['professional_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index(op.f('ix_skills_category_id'), 'skills', ['category_id'], unique=False)
    op.create_index('ix_skills_public_order', 'skills', ['status', 'is_visible', 'sort_order'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_index(op.f('ix_skills_status'), 'skills', ['status'], unique=False)
    op.create_table('social_links',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('handle', sa.String(length=160), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index(op.f('ix_social_links_profile_id'), 'social_links', ['profile_id'], unique=False)
    op.create_index('ix_social_links_profile_order', 'social_links', ['profile_id', 'sort_order'], unique=False)
    op.create_table('experience_projects',
    sa.Column('experience_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'project_id')
    )
    op.create_table('experience_skills',
    sa.Column('experience_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'skill_id')
    )
    op.create_table('impact_metrics',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('experience_id', sa.Uuid(), nullable=True),
    sa.Column('subject_label', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=80), nullable=True),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=2048), nullable=True),
    sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('NOT is_approved OR (evidence_reference IS NOT NULL AND length(trim(evidence_reference)) > 0)', name='ck_metric_approval_evidence'),
    sa.CheckConstraint('project_id IS NOT NULL OR experience_id IS NOT NULL OR (subject_label IS NOT NULL AND length(trim(subject_label)) > 0)', name='ck_metric_subject'),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index(op.f('ix_impact_metrics_experience_id'), 'impact_metrics', ['experience_id'], unique=False)
    op.create_index(op.f('ix_impact_metrics_project_id'), 'impact_metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_impact_metrics_status'), 'impact_metrics', ['status'], unique=False)
    op.create_index('ix_metrics_project', 'impact_metrics', ['project_id', 'sort_order'], unique=False)
    op.create_index('ix_metrics_public_order', 'impact_metrics', ['status', 'is_visible', 'sort_order'], unique=False)
    op.create_table('project_media',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('storage_key IS NOT NULL OR external_url IS NOT NULL', name='ck_project_media_source'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_project_media_order', 'project_media', ['project_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_project_media_project_id'), 'project_media', ['project_id'], unique=False)
    op.create_table('project_sectors',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'sector_id')
    )
    op.create_table('project_skills',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'skill_id')
    )
    op.create_table('testimonials',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('experience_id', sa.Uuid(), nullable=True),
    sa.Column('subject_label', sa.String(length=200), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('attribution_name', sa.String(length=160), nullable=False),
    sa.Column('attribution_title', sa.String(length=160), nullable=True),
    sa.Column('attribution_organization', sa.String(length=200), nullable=True),
    sa.Column('source_reference', sa.String(length=2048), nullable=True),
    sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seed_key', sa.String(length=160), nullable=True),
    sa.Column('seed_source', sa.String(length=32), nullable=True),
    sa.Column('seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'hidden', 'archived', name='publicationstatus', native_enum=False, create_constraint=True, length=16), server_default='draft', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('noindex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('NOT is_approved OR (source_reference IS NOT NULL AND length(trim(source_reference)) > 0)', name='ck_testimonial_approval_source'),
    sa.CheckConstraint('project_id IS NOT NULL OR experience_id IS NOT NULL OR (subject_label IS NOT NULL AND length(trim(subject_label)) > 0)', name='ck_testimonial_subject'),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key')
    )
    op.create_index(op.f('ix_testimonials_experience_id'), 'testimonials', ['experience_id'], unique=False)
    op.create_index('ix_testimonials_project', 'testimonials', ['project_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_testimonials_project_id'), 'testimonials', ['project_id'], unique=False)
    op.create_index('ix_testimonials_public_order', 'testimonials', ['status', 'is_visible', 'sort_order'], unique=False)
    op.create_index(op.f('ix_testimonials_status'), 'testimonials', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testimonials_status'), table_name='testimonials')
    op.drop_index('ix_testimonials_public_order', table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_project_id'), table_name='testimonials')
    op.drop_index('ix_testimonials_project', table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_experience_id'), table_name='testimonials')
    op.drop_table('testimonials')
    op.drop_table('project_skills')
    op.drop_table('project_sectors')
    op.drop_index(op.f('ix_project_media_project_id'), table_name='project_media')
    op.drop_index('ix_project_media_order', table_name='project_media')
    op.drop_table('project_media')
    op.drop_index('ix_metrics_public_order', table_name='impact_metrics')
    op.drop_index('ix_metrics_project', table_name='impact_metrics')
    op.drop_index(op.f('ix_impact_metrics_status'), table_name='impact_metrics')
    op.drop_index(op.f('ix_impact_metrics_project_id'), table_name='impact_metrics')
    op.drop_index(op.f('ix_impact_metrics_experience_id'), table_name='impact_metrics')
    op.drop_table('impact_metrics')
    op.drop_table('experience_skills')
    op.drop_table('experience_projects')
    op.drop_index('ix_social_links_profile_order', table_name='social_links')
    op.drop_index(op.f('ix_social_links_profile_id'), table_name='social_links')
    op.drop_table('social_links')
    op.drop_index(op.f('ix_skills_status'), table_name='skills')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index('ix_skills_public_order', table_name='skills')
    op.drop_index(op.f('ix_skills_category_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index('uq_resume_current', table_name='resume_versions', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current = 1'))
    op.drop_index(op.f('ix_resume_versions_status'), table_name='resume_versions')
    op.drop_index(op.f('ix_resume_versions_profile_id'), table_name='resume_versions')
    op.drop_index('ix_resume_versions_profile_created', table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index('ix_projects_public_featured', table_name='projects')
    op.drop_index('ix_projects_public_date', table_name='projects')
    op.drop_index(op.f('ix_projects_category_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('uq_portrait_primary_per_profile', table_name='portrait_assets', postgresql_where=sa.text('is_primary AND is_active'), sqlite_where=sa.text('is_primary = 1 AND is_active = 1'))
    op.drop_index('ix_portrait_assets_profile_order', table_name='portrait_assets')
    op.drop_index(op.f('ix_portrait_assets_profile_id'), table_name='portrait_assets')
    op.drop_table('portrait_assets')
    op.drop_table('experience_sectors')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index('ix_articles_public_date', table_name='articles')
    op.drop_index(op.f('ix_articles_hero_media_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_admin_sessions_user_active', table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_token_hash'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_expires_at'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_admin_user_id'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_index(op.f('ix_sectors_status'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_slug'), table_name='sectors')
    op.drop_index('ix_sectors_public_order', table_name='sectors')
    op.drop_table('sectors')
    op.drop_index('uq_profiles_primary', table_name='profiles', postgresql_where=sa.text('is_primary'), sqlite_where=sa.text('is_primary = 1'))
    op.drop_index(op.f('ix_profiles_status'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_professional_categories_status'), table_name='professional_categories')
    op.drop_index(op.f('ix_professional_categories_slug'), table_name='professional_categories')
    op.drop_index('ix_categories_public_order', table_name='professional_categories')
    op.drop_table('professional_categories')
    op.drop_index('ix_navigation_public_order', table_name='navigation_items')
    op.drop_index(op.f('ix_navigation_items_status'), table_name='navigation_items')
    op.drop_table('navigation_items')
    op.drop_index(op.f('ix_media_assets_status'), table_name='media_assets')
    op.drop_index('ix_media_assets_public', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_login_attempts_throttle', table_name='login_attempts')
    op.drop_index('ix_login_attempts_ip_recent', table_name='login_attempts')
    op.drop_index('ix_login_attempts_identifier_recent', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_occurred_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index('uq_homepage_sections_position', table_name='homepage_sections')
    op.drop_index(op.f('ix_homepage_sections_status'), table_name='homepage_sections')
    op.drop_index('ix_homepage_sections_public_order', table_name='homepage_sections')
    op.drop_index(op.f('ix_homepage_sections_feature_key'), table_name='homepage_sections')
    op.drop_table('homepage_sections')
    op.drop_index(op.f('ix_feature_settings_key'), table_name='feature_settings')
    op.drop_index(op.f('ix_feature_settings_archived_at'), table_name='feature_settings')
    op.drop_table('feature_settings')
    op.drop_index(op.f('ix_experiences_status'), table_name='experiences')
    op.drop_index('ix_experiences_public_dates', table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_education_status'), table_name='education')
    op.drop_index('ix_education_public_dates', table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_certifications_status'), table_name='certifications')
    op.drop_index('ix_certifications_public_order', table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
